on:
  create:
    gex: '^v[0-9]+\.[0-9]+\.[0-9]+$'
jobs:
  test_job:
    runs-on: ubuntu-latest
    name: test
    steps:
      # - name: test
      #   id: test
      #   uses: 0xchina/action@master
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3

